# -*- coding: utf-8 -*-
"""Imagetransformations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YR0rvrQwlDvzL8Hzm-x6JYGpkdflCEqK

# Image Transformations

----------------

+ CIFP Pau Casesnoves (2021/2022)
+ Professor    : Antoni Oliver Gelabert
+ Degree       : Development of Web Applications (DAM) 
+ Subject      : Interface Web Design (DIW) - Multimedia elements for the web

----------------

### Resume

1. Visualization
2. Format conversion 
3. Crop 
4. Size modifications
5. Translation / rotation
6. Morphological transformations
7. Distance, area and angle measurements 
8. Binarization 
9. Color reduction
10. Color Replacement
11. Smoothing / Noise reduction
12. Region Clone
13. Histogram normalization (auto-level)
14. Gamma correction (auto-gamma)
15. Brightness / Contrast
16. Adding text
17. Line and Circle detection
18. Special effects: redeye, Cube3D, 
19. Object detection
20. Image Composition
21. Arithmetic and binary operations
22. Collage
23. Making bash script to process an image
24. Making a python program to process images
25. Process an image using GIMP

Before start, download the image which is in the following path:
https://live.staticflickr.com/7286/9059564319_374d60828a_b.jpg
"""

!wget https://live.staticflickr.com/7286/9059564319_374d60828a_b.jpg -O husky.jpg

"""### 1. Visualization

See an image with a viewer (for instance, using display, GIMP or anyother software)
"""

!apt install imagemagick > /dev/null
from IPython.display import Image
Image(filename="husky.jpg", width=600)
#!display husky.jpg
#!gimp husky.jpg
#!inkscape husky.jpg

"""### 2. Format conversion"""

!convert husky.jpg husky.png
!convert husky.jpg husky.gif

"""### 3. Crop"""

!convert husky.png -gravity North-West -crop 200x200+0+0 husky_crop_gnw_200_200_0_0.png
!convert husky.png -gravity North  -crop 200x200+0+0 husky_crop_gn_200_200_0_0.png
!convert husky.png -gravity North-East  -crop 200x200+0+0 husky_crop_gne_200_200_0_0.png
!convert husky.png -gravity Center  -crop 200x200-200+0 husky_crop_gcw_200_200_0_300.png
!convert husky.png -gravity Center  -crop 200x200+0+0 husky_crop_gc_200_200_0_0.png
!convert husky.png -gravity Center  -crop 200x200+200+0 husky_crop_gce_200_200_0_300.png
!convert husky.png -gravity South-West -crop 200x200+0+0 husky_crop_gsw_200_200_0_0.png
!convert husky.png -gravity South  -crop 200x200+0+0 husky_crop_gs_200_200_0_0.png
!convert husky.png -gravity South-East  -crop 200x200+0+0 husky_crop_gse_200_200_0_0.png
!montage -frame 5  -shadow  -geometry 300x300 -tile 3x3 husky_crop_gnw_200_200_0_0.png husky_crop_gn_200_200_0_0.png husky_crop_gne_200_200_0_0.png  husky_crop_gcw_200_200_0_300.png husky_crop_gc_200_200_0_0.png husky_crop_gce_200_200_0_300.png husky_crop_gsw_200_200_0_0.png husky_crop_gs_200_200_0_0.png husky_crop_gse_200_200_0_0.png huskymont.png

"""See more of montage operations here: https://legacy.imagemagick.org/Usage/montage/"""

from IPython.display import Image
Image(filename="huskymont.png", width=600)

"""*Activity 11. Modify this script to align the top and the bottom images playing with crop regions*

### 4. Resize
"""

!identify husky.png

!convert husky.png -resize 300x300 tinyhusky.png
!convert husky.png -resize 600x600 mediumhusky.png
Image(filename="tinyhusky.png")

!identify tinyhusky.png

Image(filename="mediumhusky.png")

!convert husky.png -size 600x600 sizedhusky.png
Image(filename="sizedhusky.png")

!identify sizedhusky.png

"""### 5. Translations and rotations

Options: -flip, -rotate, -transverse, -transpose
"""

from IPython.display import Image
!convert husky.png -flip -label "%m:%f %wx%h" huskyflip.png
!convert husky.png -rotate 45  -label "%m:%f %wx%h" huskyrotated.png
!convert husky.png -transverse -label "%m:%f %wx%h" transvershusky.png
!convert husky.png -transpose -label "%m:%f %wx%h" transposedhusky.png
!montage -frame 5  -shadow  -geometry 300x300 -tile 2x2 huskyflip.png huskyrotated.png transvershusky.png transposedhusky.png shearedhuskymont.png
Image(filename="shearedhuskymont.png")

from IPython.display import Image
!convert husky.png -rotate 15 -label "%m:%f %wx%h" rhuskyr01.png
!convert husky.png -rotate 30  -label "%m:%f %wx%h" rhuskyr02.png
!convert husky.png -rotate 45  -label "%m:%f %wx%h" rhuskyr03.png
!convert husky.png -rotate 60  -label "%m:%f %wx%h" rhuskyr04.png
!convert husky.png -rotate 75  -label "%m:%f %wx%h" rhuskyr05.png
!convert husky.png -rotate 90  -label "%m:%f %wx%h" rhuskyr06.png
!convert husky.png -rotate 105  -label "%m:%f %wx%h" rhuskyr07.png
!convert husky.png -rotate 120  -label "%m:%f %wx%h" rhuskyr08.png
!convert husky.png -rotate 135  -label "%m:%f %wx%h" rhuskyr09.png
!convert husky.png -rotate 150  -label "%m:%f %wx%h" rhuskyr10.png
!convert husky.png -rotate 165  -label "%m:%f %wx%h" rhuskyr11.png
!convert husky.png -rotate 180  -label "%m:%f %wx%h" rhuskyr12.png
!montage -frame 5  -shadow  -geometry 300x300 -tile 3x4 rhuskyr*.png rotatedhuskymont.png
Image(filename="rotatedhuskymont.png", width=900)

"""### 6. Image Deformations

Options:  -shear
"""

from IPython.display import Image
!convert husky.png -shear 0x5  -label '%f' shearedhusky1.png
!convert husky.png -shear 20x5  -label '%f' shearedhusky2.png
!convert husky.png -shear 20x5  -shear 50x0 -label '%f' shearedhusky3.png
!convert husky.png -shear 10x10  -shear 50x25 -label '%f' shearedhusky4.png
!montage -frame 5  -shadow  -geometry 300x300 -tile 2x2 shearedhusky1.png shearedhusky2.png shearedhusky3.png shearedhusky4.png shearedhuskymont.png
Image(filename="shearedhuskymont.png")

"""*Activity 12: Make a GIF animation of a rotating figure with at least 20 frames*

### 7. Distance, area and angle measurements

Using GIMP and Inkscape

### 8. Threshold
"""

!convert husky.png -channel RGB -threshold 80% bwhusky80.png
!convert husky.png -channel RGB -threshold 60% bwhusky60.png
!convert husky.png -channel RGB -threshold 40% bwhusky40.png
!convert husky.png -channel RGB -threshold 20% bwhusky20.png
!montage -frame 5  -shadow  -geometry 400x400 -tile 2x2 bwhusky*png bmontbwhusky.png
Image(filename="bmontbwhusky.png")

"""Set Transparency levels"""

!convert husky.png -white-threshold 80% -transparent white husky_binarized_80pc.png
!convert husky.png -white-threshold 60% -transparent white husky_binarized_60pc.png
!convert husky.png -white-threshold 40% -transparent white husky_binarized_40pc.png
!convert husky.png -white-threshold 20% -transparent white husky_binarized_20pc.png
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x2 husky_binar*.png binhuskymont2.png
Image(filename="binhuskymont2.png", width=900)

!convert husky.png -white-threshold 80% -transparent white husky_binarized_80pc.gif
!convert husky.png -white-threshold 60% -transparent white husky_binarized_60pc.gif
!convert husky.png -white-threshold 50% -transparent white husky_binarized_50pc.gif
!convert husky.png -white-threshold 40% -transparent white husky_binarized_40pc.gif
!convert husky.png -white-threshold 20% -transparent white husky_binarized_20pc.gif
!convert -delay 70 +loop husky_bin*.gif binhuskyanim.gif
!convert binhuskyanim.gif binhuskyanim.webm
#gif=binhuskyanim.gif
Image(open('binhuskyanim.gif', 'rb').read(),width=600)
#Image(filename="binhuskyanim.webm", width=600)

!convert husky.png -set colorspace Gray -separate -average huskygray.png
Image(filename="huskygray.png", width=600)

!convert husky.png -threshold 80% husky_bwbinarized_80pc.gif
!convert husky.png -threshold 60% husky_bwbinarized_60pc.gif
!convert husky.png -threshold 50% husky_bwbinarized_50pc.gif
!convert husky.png -threshold 40% husky_bwbinarized_40pc.gif
!convert husky.png -threshold 20% husky_bwbinarized_20pc.gif
!convert -delay 70 +loop husky_bwbin*.gif binhuskyanimbw.gif
Image(open('binhuskyanimbw.gif', 'rb').read(), width=600)

"""+ http://www.fmwconcepts.com/imagemagick/kapurthresh/index.php
+ http://www.fmwconcepts.com/imagemagick/otsuthresh/index.php 
+ http://www.fmwconcepts.com/imagemagick/trianglethresh/index.php
+ http://www.fmwconcepts.com/imagemagick/2colorthresh/index.php
+ http://www.fmwconcepts.com/imagemagick/localthresh/index.php

### 9. Color reduction
"""

!convert husky.png  -dither Riemersma  -colors 2   husky_002_rm.gif
!convert husky.png  -dither Riemersma  -colors 3   husky_003_rm.gif
!convert husky.png  -dither Riemersma  -colors 4   husky_004_rm.gif
!convert husky.png  -dither Riemersma  -colors 8   husky_008_rm.gif
!convert husky.png  -dither Riemersma  -colors 16  husky_016_rm.gif
!convert husky.png  -dither Riemersma  -colors 32  husky_032_rm.gif
!convert husky.png  -dither Riemersma  -colors 64  husky_064_rm.gif
!convert husky.png  -dither Riemersma  -colors 128 husky_128_rm.gif
!convert husky.png  -dither Riemersma  -colors 255 husky_255_rm.gif
!convert -delay 70 +loop husky_*rm.gif dither_huskyanim.gif
Image(open("dither_huskyanim.gif",'rb').read(), width=600)

!montage -frame 5  -shadow  -geometry 600x600 -tile 3x3 husky_*rm.gif ditherhuskymont.png
Image(filename="ditherhuskymont.png", width=900)

"""### 10. Color Replacement

See https://legacy.imagemagick.org/Usage/color_basics/#replace

"""

!convert husky.png -fuzz 25% -fill white -opaque blue opaque_b25_husky.jpg
!convert husky.png -fuzz 50% -fill white -opaque blue opaque_b50_husky.jpg
!convert husky.png -fuzz 75% -fill white -opaque blue opaque_b75_husky.jpg
!convert husky.png -fuzz 0% -fill white -opaque blue opaque_b00_husky.jpg
!convert husky.png -fuzz 25% -fill white -opaque red opaque_r25_husky.jpg
!convert husky.png -fuzz 50% -fill white -opaque red opaque_r50_husky.jpg
!convert husky.png -fuzz 75% -fill white -opaque red opaque_r75_husky.jpg
!convert husky.png -fuzz 0% -fill white -opaque red opaque_r00_husky.jpg
!convert husky.png -fuzz 25% -fill white -opaque green opaque_g25_husky.jpg
!convert husky.png -fuzz 50% -fill white -opaque green opaque_g50_husky.jpg
!convert husky.png -fuzz 75% -fill white -opaque green opaque_g75_husky.jpg
!convert husky.png -fuzz 0% -fill white -opaque green opaque_g00_husky.jpg
!convert -delay 70 +loop opaque*.jpg huskyanim_replcolors.gif
Image(open("huskyanim_replcolors.gif",'rb').read(), width=800)

!montage -frame 5  -shadow  -geometry 500x500 -tile 4x3 opaque_*.jpg coloreplacemont.png
Image(filename="coloreplacemont.png", width=1100)

"""
### 11. Morphological transformations: noise reduction, adding noise, growth-dilate
"""



"""### 12. Region Clone

Easily perform this using GIMP

### 13. Histogram

https://legacy.imagemagick.org/Usage/color_mods/
"""

!convert husky.png -define histogram:unique-colors=true histogram:histogramhusky.jpg
Image(filename="histogramhusky.jpg", width=600)

!convert histogramhusky.jpg -strip -resize 50% -separate  histogram_%d.jpg
!montage -frame 5  -shadow  -geometry 500x500 -tile 3x1  histogram_*jpg monthistogram.jpg
Image(filename="monthistogram.jpg", width=900)

"""### 14. Gamma Correction

linear operators : -normalize", "-contrast-stretch", and "-linear-stretch"
non-linear operators : -equalize"
https://legacy.imagemagick.org/Usage/color_mods/
"""

!convert husky.png -gamma 0.2 husky_gamma_02.jpg
!convert husky.png -gamma 0.5 husky_gamma_05.jpg
!convert husky.png -gamma 1.0 husky_gamma_10.jpg
!convert husky.png -gamma 1.5 husky_gamma_15.jpg
!convert husky.png -gamma 2.0 husky_gamma_20.jpg
!convert husky.png -gamma 2.2 husky_gamma_22.jpg
!montage -frame 5  -shadow  -geometry 400x400 -tile 3x2 husky_gamma*.jpg montagegamma.png
Image(filename="montagegamma.png", width=900)

!convert husky.png -gamma 0.2,0.5,1.5 husky_gamma2_02.jpg
!convert husky.png -gamma 0.5,1.5,1.5 husky_gamma2_05.jpg
!convert husky.png -gamma 1.0,2.0,1.5 husky_gamma2_10.jpg
!convert husky.png -gamma 2.0,0.5,1.5 husky_gamma2_15.jpg
!convert husky.png -gamma 1.5,1.5,0.5 husky_gamma2_20.jpg
!convert husky.png -gamma 0.5,2.0,1.0 husky_gamma2_22.jpg
!montage -frame 5  -shadow  -geometry 400x400 -tile 3x2 husky_gamma2*.jpg montagegamma2.png
Image(filename="montagegamma2.png", width=900)

!convert husky.png -auto-level husky_autolevel.png
!convert husky.png -contrast -contrast -contrast -contrast husky_contrastb4.png
!convert husky.png -equalize husky_equalize.png
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x2 husky.png husky_autolevel.png husky_contrastb4.png husky_equalize.png montageautolevel.png
Image(filename="montageautolevel.png", width=900)

!convert husky.png -equalize husky_equalize.png

!convert husky_contrastb4.png -define histogram:unique-colors=true histogram:histogramhusky_contrastb4.jpg
!convert husky_equalize.png -define histogram:unique-colors=true histogram:histogramhusky_equalize.jpg
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x1 histogram:histogramhusky_contrastb4.jpg histogramhusky_equalize.jpg histogramhuskymont.jpg
Image(filename="histogramhuskymont.jpg", width=900)

!convert husky_equalize.png -define histogram:unique-colors=true -format %c histogram:info:- > hist_picture.txt
!head -n 20 hist_picture.txt

!gimp husky_contrastb4.png

"""## Encipher-Decipher images

https://imagemagick.org/script/cipher.php

https://legacy.imagemagick.org/Usage/transform/#encipher

Using a text file:
"""

!echo "diw2122" > passphrase.txt
!convert husky.png -encipher passphrase.txt huskycyphtxt.png 
!display huskycyphtxt.png
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x1 husky.png huskycyphtxt.png huskyencrmont.jpg
Image(filename="huskyencrmont.jpg", width=900)

"""Using another image:"""

!convert husky.jpg -resize 30x30 -solarize 50% -swirl 250 husky30.gif
!convert husky.png -encipher husky30.gif huskyimciph.png

#!wget -O homer.jpg
#!convert homer.jpg -resize 30x30 -solarize 50% -swirl 250 encykey.gif
#!convert homer.jpg -encipher encykey.gif encypim.png

"""# Activity 13. 

Using: 

+ The encypher key: encykey.gif 
+ The encyphed image: encypim.png
    
Decyph it...and put the commands used and the result image in your workbook

### Hole Filling

https://legacy.imagemagick.org/Usage/masking/
"""



"""### Transparency

"""

!convert husky.png  -alpha set -background none -channel A -evaluate multiply 0.75 +channel  husky75alpha.png
!convert husky.png  -alpha set -background none -channel A -evaluate multiply 0.50 +channel  husky50alpha.png
!convert husky.png  -alpha set -background none -channel A -evaluate multiply 0.25 +channel  husky25alpha.png
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x2 husky.png husky*alpha.png huskytranspsmont.jpg
Image(filename="huskytranspsmont.jpg", width=900)
#!convert husky.png  -transparent white resized_transp_cont.png

"""### Special effects"""

!convert husky.png -swirl 180 huskyswirl180.png
!convert husky.png -paint 5 huskypaint5.png
!convert husky.png -solarize 50 huskysolarize50.png
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x2 husky.png huskyswirl180.png huskypaint5.png huskysolarize50.png huskyeffectsmont.jpg
Image(filename="huskyeffectsmont.jpg", width=900)

!convert husky.jpg  -modulate 60  modulate_off.png
Image(filename="modulate_off.png", width=600)

"""### Backgroud creation: 

https://legacy.imagemagick.org/Usage/backgrounds/

### Other special Effects

+ Advanced effects: https://legacy.imagemagick.org/Usage/advanced/
+ Variable Blur: http://www.fmwconcepts.com/imagemagick/variableblur/index.php
+ Kaleidoscopic: 
    + http://www.fmwconcepts.com/imagemagick/kaleidoscopic/index.php
    + http://www.fmwconcepts.com/imagemagick/kaleidoscope/index.php
+ Vintage : http://www.fmwconcepts.com/imagemagick/vintage3/index.php 
+ Vignete : http://www.fmwconcepts.com/imagemagick/vignette3/index.php
+ Sketch  : http://www.fmwconcepts.com/imagemagick/sketch/index.php  
+ Noise Reduction : http://www.fmwconcepts.com/imagemagick/denoise/index.php
+ Noise Cleaner   : http://www.fmwconcepts.com/imagemagick/noisecleaner/index.php
+ Adding Noise : https://imagemagick.org/script/command-line-options.php#noise
+ Erosion-Dilation: 
    + http://www.fmwconcepts.com/imagemagick/morphology/index.php
    + https://legacy.imagemagick.org/Usage/morphology/
+ Corner detection : http://www.fmwconcepts.com/imagemagick/corners/index.php
+ Hough Lines : http://www.fmwconcepts.com/imagemagick/houghlines/index.php
+ Fisheye to panoramic : http://www.fmwconcepts.com/imagemagick/fisheye2pano/index.php
+ Pixelize : http://www.fmwconcepts.com/imagemagick/pixelize/index.php
+ Puzzle   : http://www.fmwconcepts.com/imagemagick/puzzle/index.php
+ Shuffle  : http://www.fmwconcepts.com/imagemagick/shuffle/index.php 
+ BoxGIF : http://www.fmwconcepts.com/imagemagick/3Dbox/index.php 
+ ColorReplace : http://www.fmwconcepts.com/imagemagick/replacecolor/index.php
+ Lupe : http://www.fmwconcepts.com/imagemagick/lupe/index.php 
+ Glass efects: http://www.fmwconcepts.com/imagemagick/glasseffects/index.php
+ Texturize : http://www.fmwconcepts.com/imagemagick/texturize/index.php
+ Toonify: http://www.fmwconcepts.com/imagemagick/toonify/index.php
+ Thermography: http://www.fmwconcepts.com/imagemagick/thermography/index.php
+ pseudocolog : http://www.fmwconcepts.com/imagemagick/pseudocolor/index.php
+ Red eye     : http://www.fmwconcepts.com/imagemagick/redeye/index.php
+ Reflect     : http://www.fmwconcepts.com/imagemagick/reflect/index.php
+ Watercolor   : http://www.fmwconcepts.com/imagemagick/watercolor/index.php
+ Wharholeffect: http://www.fmwconcepts.com/imagemagick/warholeffect/index.php
+ Stained Glass : http://www.fmwconcepts.com/imagemagick/stainedglass/index.php
+ Shimmer       : http://www.fmwconcepts.com/imagemagick/shimmer/index.php

### ColorSpaces

https://imagemagick.org/script/command-line-options.php#colorspace
"""

!convert husky.jpg  -colorspace CMY  huskycspcmy.jpg
!convert husky.jpg  -colorspace CMYK huskycspcmyk.jpg
!convert husky.jpg  -colorspace HSV  huskycsphsv.jpg
!convert husky.jpg  -colorspace Gray huskycspgray.jpg
!convert husky.jpg  -colorspace HSB  huskycsphsb.jpg
!convert husky.jpg  -colorspace RGB  huskycspgrgb.jpg
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x3 huskycsp*.jpg huskycspmont.jpg
Image(filename="huskycspmont.jpg", width=600)
#!convert image.jpg -set colorspace Gray -separate -average gray_image.tif

"""### Combining Images

https://legacy.imagemagick.org/Usage/compose/

+ Adding watermark
+ averaging multiple images
+ adding images
+ image difference
+ Binary operations: AND, OR, XOR,...
+ Adding text to images

https://legacy.imagemagick.org/Usage/layers/

+ Example of aligning two images and overlap
+ Example of adding text to an image
"""

#!composite -gravity center .\resized_transp_cont.png Mallorca_carretera_transp.png sortida.png
#!composite -gravity center .\mallorca_solapable.png resized_transp_cont.png sortida.png
#!convert image.jpg -fill black +opaque yellow -fill white -opaque yellow -print "yellow sun pixels =%[fx:w*h*mean]\n" im.jpg
#!compare -fuzz 50% -density 300 image1.jpg image2.jpg -compose src diff_50thr.jpg

"""### Image Information"""

!identify -verbose husky.jpg

"""### Edge detection
### Contours
### Box - measure
### Line detector
### Circle detector
### Corner detector
### Object detection

### Image Optimizations

see also: https://legacy.imagemagick.org/Usage/thumbnails/
"""

!wget https://live.staticflickr.com/7286/9059564319_374d60828a_b.jpg -O husky.jpg
!convert -strip -interlace Plane -gaussian-blur 0.05 -quality 85% husky.jpg huskyopt.jpg
!convert husky.jpg  -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB huskyopt2.jpg
!convert husky.jpg  -sampling-factor 4:2:0 -strip -quality 15 -interlace JPEG -colorspace RGB huskyopt3.jpg
!montage -frame 5  -shadow  -geometry 500x500 -tile 2x2  husky.jpg huskyopt.jpg huskyopt2.jpg huskyopt3.jpg huskyoptmont.jpg
Image(filename="huskyoptmont.jpg", width=900)

!du -h huskyopt* husky.jpg

"""### Photo improvement: 
https://legacy.imagemagick.org/Usage/photos/
"""



"""### Advanced animations:

https://legacy.imagemagick.org/Usage/warping/

### A bash script to process an image or several images
"""



"""Advanced scripting: 

https://legacy.imagemagick.org/Usage/api/

### Exercices

Given the following Image and using image processing software, answer this questions:

+ What is the format?
+ What is the physical size?
+ How many pixels does the image have?
+ What is the colorspace of the image?
+ What is the resolution of the image?
+ What is the memory size?
+ Is a vector graphics or raster?
+ What is the Blue channel value of the pixel (150,200)? Express in 8-bit 
+ How many pixels have the value between the region from 20 to 60?
+ What is the average Green value of the image?
+ Vectorize the image to see it in SVG
+ Make a montage of 9 images (3x3) using -geometry 500:
    1. a rotated image (45 degrees)
    2. Gamma corrected image
    3. 50% transparency
    4. A 4-color reduction
    5. Convert to grayscale
    6. Convert to cymk
    7. Crop 400x400 pixels from the center
    8. Blurred image
    9. Cloned object
+ Make a GIF using the next images from the original (using 50 as delay):
    1. The original image
    2. Black and White converted image at 30%
    3. Black and White converted image at 60%
    4. Only Red Channel
+ Make a rotated world GIF from the original image
+ What is the hidden message? You must use the original image.
+ Make an script which automatically add a watermark over all JPG Images in the current directory on the bottom right corner. Also, put the date and filename as label format in each image.
+ Use the following text file as a key for decipher this image
+ Use the following image as a key for decipher this image

### Resources:

+ GIMP   : https://docs.gimp.org/2.10/en/
    + Batch mode : 
        + https://www.gimp.org/tutorials/Basic_Batch/ 
        + https://www.rpi.edu/dept/acm/packages/gimp/gimp-1.2.3/help/C/command_line.html
    + Python Developers :
        + https://www.gimp.org/docs/python/index.html
        + https://pythonrepo.com/repo/isman7-gimp-python-development
+ OpenCV : 
    + https://opencv24-python-tutorials.readthedocs.io/en/latest/py_tutorials/py_core/py_table_of_contents_core/py_table_of_contents_core.html
    + https://opencv24-python-tutorials.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_table_of_contents_imgproc/py_table_of_contents_imgproc.html 
    + https://opencv24-python-tutorials.readthedocs.io/en/latest/py_tutorials/py_photo/py_table_of_contents_photo/py_table_of_contents_photo.html
+ Convert examples: https://legacy.imagemagick.org/Usage/
    + Montage          : https://legacy.imagemagick.org/Usage/montage/
    + GIF animations   : https://legacy.imagemagick.org/Usage/anim_basics/
    + Color Replacement: https://legacy.imagemagick.org/Usage/color_basics/#replace
    + Annotations      : https://legacy.imagemagick.org/Usage/annotating/
"""

